"""Slack notification tool (requires approval)."""

import json
from typing import Any

from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError

from ..config import get_settings
from .base import ActionTool


class SlackTool(ActionTool):
    """Tool for posting messages to Slack (requires user approval)."""

    requires_approval: bool = True

    def __init__(self) -> None:
        """Initialize Slack client."""
        settings = get_settings()
        self._client = WebClient(token=settings.slack_bot_token)
        self._default_channel = settings.slack_default_channel

    @property
    def name(self) -> str:
        return "post_slack_message"

    @property
    def description(self) -> str:
        return """Post a message to Slack.

IMPORTANT: This action requires user approval before execution.
Use this tool to share investigation findings and incident summaries with the team.

The message supports Slack markdown formatting:
- *bold*, _italic_, ~strikethrough~
- `code` and ```code blocks```
- Lists with bullet points
- Links: <url|text>

You can also use Slack Block Kit for rich formatting."""

    @property
    def input_schema(self) -> dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string",
                    "description": f"Slack channel ID or name (default: {self._default_channel})",
                },
                "text": {
                    "type": "string",
                    "description": "Message text (supports Slack markdown)",
                },
                "blocks": {
                    "type": "array",
                    "description": "Optional Slack Block Kit blocks for rich formatting",
                    "items": {"type": "object"},
                },
                "thread_ts": {
                    "type": "string",
                    "description": "Thread timestamp to reply in a thread",
                },
            },
            "required": ["text"],
        }

    async def execute(
        self,
        text: str,
        channel: str | None = None,
        blocks: list[dict[str, Any]] | None = None,
        thread_ts: str | None = None,
        **kwargs: Any,
    ) -> str:
        """Post a message to Slack."""
        try:
            target_channel = channel or self._default_channel

            post_kwargs: dict[str, Any] = {
                "channel": target_channel,
                "text": text,
            }

            if blocks:
                post_kwargs["blocks"] = blocks

            if thread_ts:
                post_kwargs["thread_ts"] = thread_ts

            response = self._client.chat_postMessage(**post_kwargs)

            return json.dumps(
                {
                    "success": True,
                    "channel": response["channel"],
                    "timestamp": response["ts"],
                    "message": "Message posted successfully",
                    "permalink": self._get_permalink(response["channel"], response["ts"]),
                },
                indent=2,
            )

        except SlackApiError as e:
            return json.dumps(
                {
                    "success": False,
                    "error": f"Slack API error: {e.response['error']}",
                    "details": str(e),
                }
            )
        except Exception as e:
            return json.dumps({"success": False, "error": str(e)})

    def _get_permalink(self, channel: str, ts: str) -> str | None:
        """Get permalink for a message."""
        try:
            response = self._client.chat_getPermalink(channel=channel, message_ts=ts)
            return response.get("permalink")
        except SlackApiError:
            return None

    def format_investigation_report(
        self,
        service: str,
        environment: str,
        summary: str,
        root_causes: list[dict[str, Any]],
        recommendations: list[str],
    ) -> tuple[str, list[dict[str, Any]]]:
        """Format an investigation report as Slack blocks.

        Returns:
            Tuple of (fallback_text, blocks)
        """
        fallback_text = f"[{environment.upper()}] {service} - Investigation Report: {summary}"

        blocks: list[dict[str, Any]] = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f":mag: Investigation Report - {service}",
                    "emoji": True,
                },
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": f"*Environment:* `{environment}` | *Generated by:* CloudWatch Triage Agent",
                    }
                ],
            },
            {"type": "divider"},
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"*Summary*\n{summary}"},
            },
            {"type": "divider"},
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": "*Root Cause Candidates*"},
            },
        ]

        # Add root causes
        for i, cause in enumerate(root_causes[:3], 1):
            confidence_emoji = {
                "high": ":red_circle:",
                "medium": ":large_orange_circle:",
                "low": ":white_circle:",
            }.get(cause.get("confidence", "low"), ":white_circle:")

            evidence_text = "\n".join(f"  - {e}" for e in cause.get("evidence", [])[:3])

            blocks.append(
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*#{i}* {confidence_emoji} {cause.get('summary', 'Unknown')}\n{evidence_text}",
                    },
                }
            )

        # Add recommendations
        if recommendations:
            blocks.append({"type": "divider"})
            rec_text = "\n".join(f"• {r}" for r in recommendations[:5])
            blocks.append(
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*Recommended Actions*\n{rec_text}",
                    },
                }
            )

        return fallback_text, blocks
